### ISSUE TITLE
Add error snackbar for API errors

### ISSUE THREAD

**Issue by shorsher** [hyperledger-labs/firefly-ui#52]
Currently, the user will be not be alerted when API requests return an error. Instead, we should surface an error snackbar (https://material-ui.com/components/snackbars/) with a description of the error.

**Comment by asharonbaltazar** [comment]
Hi 👋,

I'd like to contribute to your repo. Is it the fetching done in the [Dashboard](https://github.com/hyperledger-labs/firefly-ui/blob/main/src/views/Dashboard.tsx)? I noticed there's no `.catch` function.

I also see you changed the issue title from something that mentioned `Context`. Do you have anything specific in mind in regards to showing this snackbar? 

Appreciate your response in advance!
